### ISSUE TITLE
Uncharted 4 PS4 v1.33 patch unpacking error

### ISSUE THREAD

**Issue by ColbyDash** [rm-NoobInCoding/UnPSARC#25]
Out of all of the .psarc files included with the v1.33 patch, patch1-13.psarc produces the following error for a lot of files throughout the entire extraction process:
> Error:Attempted to read past the end of the stream.

If it helps, U4.PSARC.Tool spits out more details on the error despite being designed for the Legacy of Thieves Collection:
> Unhandled Exception: System.IO.IOException: I/O error occurred.
   at U4.Unpacker.Helpers.ReadBytes(Stream stream, Int32 count)
   at U4.Unpacker.Helpers.ReadUInt16(Stream stream, Boolean bBigEndian)
   at U4.Unpacker.PsarcChunks.iReadData(FileStream TPsarStream, PsarcHeader m_Header, PsarcEntry m_Entry, Int32[] m_LengthsTable)
   at U4.Unpacker.PsarcUnpack.iDoIt(String m_Archive, String m_DstFolder)
   at U4.Unpacker.Program.Main(String[] args)

**Comment by ColbyDash** [comment]
The patch1-13.psarc that was dumped from my PS4 must've been corrupted somewhat because another patch1-13.psarc that I've managed to extract from my PC works just fine without any errors. Apologies for the premature issue creation. Lol
