### ISSUE TITLE
Ghost of Tsushima - MOD

### ISSUE THREAD

**Issue by DanialPahlavan** [rm-NoobInCoding/UnPSARC#6]
### Game Name
Ghost of Tsushima

### Issue Description
I am encountering an error when trying to unpack `.psarc` files using the UnPSARC tool for the game Ghost of Tsushima.

### Data Files List
The list of data files can be found in the following directory structure:
- \cache_pc\psarc
![image](https://github.com/rm-NoobInCoding/UnPSARC/assets/1260701/2db5b697-f9ee-458d-aa96-763dcb04e2a9)

### Root Folder Files List
The list of files in the root folder is as follows:
- Root Folder Files Structure
![image](https://github.com/rm-NoobInCoding/UnPSARC/assets/1260701/380f621b-4291-4f4e-8454-19d5077cc0ae)

### Error Encountered
The following error occurs during the unpacking process:
UnPSARC (PSARC Archive Tool For Uncharted4 PC)
By NoobInCoding
https://github.com/rm-NoobInCoding/UnPSARC

Unpacking gapack_misc_a.psarc...

Unhandled Exception: System.Exception: Not valid PSARC file! Magic:DSAR
   at UnPSARC.PSARC.Read()
   at UnPSARC.Archive.Unpack(Stream ArchiveRaw, String Folder)
   at UnPSARC.Program.UnpackArchiveFile(String inputPath, String outputDirectory)
   at UnPSARC.Program.Main(String[] args)
   
### Additional Information
I am unsure which `.dll` file is required for using the uncompressed data of this game. Any assistance in resolving this issue would be greatly appreciated.

**Comment by DanialPahlavan** [comment]
thanks ❤️
